run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofmt:
    simplify: true
  goimports:
    local-prefixes: webring
  revive:
    min-confidence: 0
  govet:
    enable:
      - shadow
    disable:
      - fieldalignment
  ineffassign:
    check-exported: false
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  unparam:
    check-exported: false
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
  depguard:
    rules:
      main:
        deny:
          # Intentionally empty - allow all imports for this project
          - pkg: ""

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
    - path: cmd/
      linters:
        - gochecknoinits
    - text: "weak cryptographic primitive"
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0