version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stdout
      print-issued-lines: true
      print-linter-name: true

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - webring

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    goconst:
      min-len: 3
      min-occurrences: 10

    gocritic:
      enabled-tags: [diagnostic, experimental, opinionated, performance, style]

    govet:
      enable: [shadow]
      disable: [fieldalignment]

    lll:
      line-length: 120

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

    unparam:
      check-exported: false
