ALTER TABLE sites ADD COLUMN slug TEXT UNIQUE;
UPDATE sites SET slug = id;
ALTER TABLE sites ALTER COLUMN slug SET NOT NULL;

-- Deferred id uniqueness
ALTER TABLE sites DROP CONSTRAINT sites_pkey;
ALTER TABLE sites ADD PRIMARY KEY (slug);
ALTER TABLE sites ADD CONSTRAINT sites_unique_id
    UNIQUE (id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE sites ALTER COLUMN id SET NOT NULL;
